// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-AvrQf4fBjzJG9zXJCtAvYhfc-IEBTw',
    appId: '1:912450884092:web:d06fcfcfd368b1c2d32279',
    messagingSenderId: '912450884092',
    projectId: 'chatapp-7c011',
    authDomain: 'chatapp-7c011.firebaseapp.com',
    databaseURL: 'https://chatapp-7c011-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-7c011.appspot.com',
    measurementId: 'G-VR3E134226',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV6bMaOawV9a_TT2ZqlG6CQ4fE6eGcDdA',
    appId: '1:912450884092:android:44c7d0ff3cdc85dcd32279',
    messagingSenderId: '912450884092',
    projectId: 'chatapp-7c011',
    databaseURL: 'https://chatapp-7c011-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-7c011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF1_0V6HlV7Z77QiMWjfAqLpBOKu1gXcA',
    appId: '1:912450884092:ios:ab53d8db50d2c920d32279',
    messagingSenderId: '912450884092',
    projectId: 'chatapp-7c011',
    databaseURL: 'https://chatapp-7c011-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-7c011.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
